import pandas as pd

prices_dict = {
    "res": "ok",
    "services": [
        {
            "name": "Lip wax",
            "description": "null",
            "price_start": "15",
            "price_end": "15",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Upper legs back strip",
            "description": "null",
            "price_start": "30",
            "price_end": "30",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Celestial signature Clay mask/ body wrap",
            "description": "Relax into your day with our ultimate self care  clay mask infused with sage, vitamins and camomile has long been celebrated for its ability to detoxify and soften skin, and improve Your lymphatic system, paired with essential oils.\nFollowing a Cocooned wrap, then a full body lotion application after to transcend your body, mind and soul this journey promises powerful body renewal treatment.\n90 mins \n\u200b",
            "price_start": "230",
            "price_end": "230",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Lower lip",
            "description": "null",
            "price_start": "10",
            "price_end": "10",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Custom facial and body wrap",
            "description": "Customized facial of your choice, including essential oil, steamer, hot towels, cold compresses face mask, amethyst eye mask.\nComes with a full arm scrub and lotion application. \nFollowed by a cocooning body wrap excellent for detoxification and relaxation.\nRejuvenation for your day. 50 mins ",
            "price_start": "160",
            "price_end": "160",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Brazilian wax pass",
            "description": "null",
            "price_start": "0",
            "price_end": "0",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Facial- Spiced golden pear with frankincense maks",
            "description": "null",
            "price_start": "125",
            "price_end": "125",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Facial- Artic cranberry enzyme/winter mask",
            "description": "null",
            "price_start": "125",
            "price_end": "125",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Add on High frequency facial",
            "description": "null",
            "price_start": "30",
            "price_end": "30",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Groupon 1st time Brazilian- will honor sale pay in store.",
            "description": "null",
            "price_start": "31",
            "price_end": "31",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Facial-swiss pine enzyme paired with a white birch mask",
            "description": "null",
            "price_start": "125",
            "price_end": "125",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Groupon Brazilian voucher",
            "description": "null",
            "price_start": "0",
            "price_end": "0",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Butt strip",
            "description": "null",
            "price_start": "15",
            "price_end": "15",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Facial-Vanilla facial, with orange brightning enzyme!",
            "description": "null",
            "price_start": "125",
            "price_end": "125",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Facial- Green tea hydrating mask with brightning enzyme",
            "description": "null",
            "price_start": "125",
            "price_end": "125",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Facial- White peach nourishing mask",
            "description": "null",
            "price_start": "125",
            "price_end": "125",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Facial-Silver or 24k Gold hydrating facial",
            "description": "null",
            "price_start": "145",
            "price_end": "145",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "24 k gold or silver add on",
            "description": "null",
            "price_start": "30",
            "price_end": "30",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Celestial signiture blue lotus scrub",
            "description": "Celestial Beauty\u2019s  signature service \nDead Sea salt scrub and jojoba oil infused with blue lotus. Providing detoxification, excellent for your lymphatic system and soften skin, improve circulation and generally ease life\u2019s aches and pains. \nWhen paired with essential oils and a infused gem quartz crystal essence.\nFollowing a full body lotion application after to transcend your body specifically chosen to enhance the energy of your unique treatment, this custom journey promises powerful Experience a total body renewal treatment. \n90 mins \n\u200b",
            "price_start": "230",
            "price_end": "230",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Nose",
            "description": "null",
            "price_start": "15",
            "price_end": "15",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Back wax full",
            "description": "null",
            "price_start": "85",
            "price_end": "85",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Bikini line",
            "description": "Bikini line waxing using premium hard wax for sensitive skin includes  hair removal just on very top and sides. ",
            "price_start": "55",
            "price_end": "55",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Brow wax",
            "description": "null",
            "price_start": "22",
            "price_end": "22",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Shoulder",
            "description": "null",
            "price_start": "20",
            "price_end": "20",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Inner thighs",
            "description": "null",
            "price_start": "15",
            "price_end": "15",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Vagacial/bikini facial",
            "description": "Vagacial- bikini facial, includes Steamer, \nbikini mask, hot towels, bootie warmers for your feet, also includes hand and arm massage, Vagacials are great for ingrown hairs and bumps and hyperpigmentation.  \n35 min service ",
            "price_start": "125",
            "price_end": "125",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Lower Legs",
            "description": "null",
            "price_start": "60",
            "price_end": "60",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Back custom facial",
            "description": "null",
            "price_start": "150",
            "price_end": "150",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Nipples wax",
            "description": "null",
            "price_start": "15",
            "price_end": "15",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Full stomach",
            "description": "null",
            "price_start": "40",
            "price_end": "40",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Brow Tinting",
            "description": "Henna brow tinting, excellent for sensitive skin is natural color pigments. ",
            "price_start": "40",
            "price_end": "40",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Custom Facial",
            "description": " 50 min relaxation Customized Facial, includes steamer, customized choice for facial mask, massage both on face, neck and arms includes custom consultation for skin care goals.",
            "price_start": "125",
            "price_end": "125",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Arms Full",
            "description": "null",
            "price_start": "65",
            "price_end": "65",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Lower back strip",
            "description": "null",
            "price_start": "22",
            "price_end": "22",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "lamination/ henna tint/wax/aftercare",
            "description": "null",
            "price_start": "130",
            "price_end": "130",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Stomach strip",
            "description": "null",
            "price_start": "15",
            "price_end": "15",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Bikini Full",
            "description": "Bikini waxing using premium hard wax for asensitive skin remove as much or as little desired hair in bikini area. ",
            "price_start": "57",
            "price_end": "57",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Full Face wax",
            "description": "null",
            "price_start": "60",
            "price_end": "60",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Booty Facial",
            "description": "Buttocks facial includes custom mask, \nessential oils body scrub infused with rose quartz essences, for uplifting your heart and energy followed by our exclusive lemon dream jojoba oil leaving your skin radiant and hydrated. Including massage on buttocks and upper legs melting all your cares away in blissful hot towels. Great for treating ingrown hairs and bumps and hyperpigmentation. \n35 mins ",
            "price_start": "150",
            "price_end": "150",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Full butt",
            "description": "null",
            "price_start": "50",
            "price_end": "50",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Full legs",
            "description": "null",
            "price_start": "100",
            "price_end": "100",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Side burns",
            "description": "null",
            "price_start": "15",
            "price_end": "15",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Cheeks",
            "description": "null",
            "price_start": "15",
            "price_end": "15",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Half arms",
            "description": "null",
            "price_start": "55",
            "price_end": "55",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Ears",
            "description": "null",
            "price_start": "15",
            "price_end": "15",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Chin",
            "description": "null",
            "price_start": "15",
            "price_end": "15",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Back strip",
            "description": "null",
            "price_start": "22",
            "price_end": "22",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Brow middle",
            "description": "null",
            "price_start": "15",
            "price_end": "15",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Neck wax",
            "description": "null",
            "price_start": "15",
            "price_end": "15",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Upper Legs",
            "description": "null",
            "price_start": "60",
            "price_end": "60",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Brazillian waxing",
            "description": "Brazilian waxing using premium hard wax for asensitive skin remove as much or as little desired hair in bikini area, also includes the butt strip.",
            "price_start": "59",
            "price_end": "59",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Full chest wax",
            "description": "null",
            "price_start": "80",
            "price_end": "80",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Lower back",
            "description": "null",
            "price_start": "30",
            "price_end": "30",
            "pricing_type": "FIXED",
            "category": "",
        },
        {
            "name": "Full Arms",
            "description": "null",
            "price_start": "60",
            "price_end": "60",
            "pricing_type": "FIXED",
            "category": "",
        },
    ],
}

old_srvc = pd.read_csv("celestial_srvc.csv")
new_srvc = pd.DataFrame(prices_dict["services"])

merged_df = pd.merge(old_srvc, new_srvc, left_on='name', right_on='name', suffixes=('_1', '_2'))

merged_df['prices_match'] = merged_df['price_start_1'] == merged_df['price_start_2']

merged_df.to_csv("services_compare.csv")

print(0)



    
